SELECT C.CODIGO_OBJETO,
       TO_CHAR(A.DATAHORA,'DD/MM/RRRR') DATMOV,
       SUBSTR(A.HORAINI,1,5) HORAINI,
       SUBSTR(A.HORAFIM,1,5) HORAFIM,
       GOT_CALCULO_HORA(HORAINI, HORAFIM) TEMPO_PARADA,
       TRIM(A.DESCRICAO) MOTIVO,
       B.DESCRICAO DESC_CAUSA,
       C.DESCRICAO DESC_OBJETO
FROM LABORATORIO.OCORRENCIA A, LABORATORIO.CAUSAS B, LABORATORIO.OBJETO C
WHERE A.COD_GRUPOEMPRESA = 1
AND   A.COD_EMPRESA      = 20
AND   A.COD_FILIAL       = 1
AND   A.CODIGO_OBJETO in (3, 355)
AND   B.COD_GRUPOEMPRESA = A.COD_GRUPOEMPRESA
AND   B.COD_EMPRESA      = A.COD_EMPRESA
AND   B.COD_FILIAL       = A.COD_FILIAL
AND   B.CODIGO           = A.COD_CAUSA
AND   A.COD_GRUPOEMPRESA = C.COD_GRUPOEMPRESA
AND   A.COD_EMPRESA      = C.COD_EMPRESA
AND   A.COD_FILIAL       = C.COD_FILIAL
AND   A.CODIGO_OBJETO    = C.CODIGO_OBJETO
AND   TRUNC(A.DATAHORA) >= trunc(sysdate) - 15
ORDER BY A.DATAHORA DESC, A.HORAINI DESC
