SELECT NVL(B.STATUS,'RODANDO') STATUS_A,
       NVL(B.MOTIVO_A,'.') MOTIVO_A,
       NVL(B.DATAHORA_A,'.') DATAHORA_A,
       NVL(B.HORAINI_A,'.') HORAINI_A,
       NVL(B.HORAFIM_A,'.') HORAFIM_A,
       NVL(B.TEMPO_A,'.') TEMPO_A,
       NVL(C.STATUS,'RODANDO') STATUS_B,
       NVL(C.MOTIVO_B,'.') MOTIVO_B,
       NVL(C.DATAHORA_B,'.') DATAHORA_B,
       NVL(C.HORAINI_B,'.') HORAINI_B,
       NVL(C.HORAFIM_B,'.') HORAFIM_B,
       NVL(C.TEMPO_B,'.') TEMPO_B
FROM (SELECT 1 CODIGO FROM DUAL) A,
     (SELECT 1 CODIGO,
             'PARADA' STATUS,
             'Motivo: ' || TRIM(A.DESCRICAO) MOTIVO_A,
             'Parada em ' || TO_CHAR(A.DATAHORA,'DD/MM/RRRR') DATAHORA_A,
             'às ' || SUBSTR(A.HORAINI,1,5) || 'Hrs' HORAINI_A,
             SUBSTR(A.HORAFIM,1,5) HORAFIM_A,
             'Tempo total parada: ' || GOT_CALCULO_HORA(HORAINI, HORAFIM) TEMPO_A
      FROM LABORATORIO.OCORRENCIA A, LABORATORIO.CAUSAS B, LABORATORIO.OBJETO C
      WHERE A.COD_GRUPOEMPRESA = 1
      AND   A.COD_EMPRESA      = 1
      AND   A.COD_FILIAL       = 1
      AND   A.CODIGO_OBJETO    = 2
      AND   B.COD_GRUPOEMPRESA = A.COD_GRUPOEMPRESA
      AND   B.COD_EMPRESA      = A.COD_EMPRESA
      AND   B.COD_FILIAL       = A.COD_FILIAL
      AND   B.CODIGO           = A.COD_CAUSA
      AND   A.COD_GRUPOEMPRESA = C.COD_GRUPOEMPRESA
      AND   A.COD_EMPRESA      = C.COD_EMPRESA
      AND   A.COD_FILIAL       = C.COD_FILIAL
      AND   A.CODIGO_OBJETO    = C.CODIGO_OBJETO
      AND   TRUNC(A.DATAHORA) >= trunc(sysdate)-10
      AND  (A.HORAINI = A.HORAFIM OR (HORAINI IS NOT NULL AND HORAFIM IS NULL))
      AND   COD_CAUSA != 69) B,
     (SELECT 1 CODIGO,
             'PARADA' STATUS,
             'Motivo: ' || TRIM(A.DESCRICAO) MOTIVO_B,
             'Parada em ' || TO_CHAR(A.DATAHORA,'DD/MM/RRRR') DATAHORA_B,
             'às ' || SUBSTR(A.HORAINI,1,5) || 'Hrs' HORAINI_B,
             SUBSTR(A.HORAFIM,1,5) HORAFIM_B,
             'Tempo total parada: ' || GOT_CALCULO_HORA(HORAINI, HORAFIM) TEMPO_B
      FROM LABORATORIO.OCORRENCIA A, LABORATORIO.CAUSAS B, LABORATORIO.OBJETO C
      WHERE A.COD_GRUPOEMPRESA = 1
      AND   A.COD_EMPRESA      = 1
      AND   A.COD_FILIAL       = 1
      AND   A.CODIGO_OBJETO    = 3
      AND   B.COD_GRUPOEMPRESA = A.COD_GRUPOEMPRESA
      AND   B.COD_EMPRESA      = A.COD_EMPRESA
      AND   B.COD_FILIAL       = A.COD_FILIAL
      AND   B.CODIGO           = A.COD_CAUSA
      AND   A.COD_GRUPOEMPRESA = C.COD_GRUPOEMPRESA
      AND   A.COD_EMPRESA      = C.COD_EMPRESA
      AND   A.COD_FILIAL       = C.COD_FILIAL
      AND   A.CODIGO_OBJETO    = C.CODIGO_OBJETO
      AND   TRUNC(A.DATAHORA) >= trunc(sysdate)-10
      AND  (A.HORAINI = A.HORAFIM OR (HORAINI IS NOT NULL AND HORAFIM IS NULL))
      AND   COD_CAUSA != 69
      AND   ROWNUM <= 1) C
WHERE A.CODIGO = B.CODIGO (+)
AND   A.CODIGO = C.CODIGO (+)
