SELECT TRIM(NOME_VARIAVEL) AS VAR,
       MAX(CASE WHEN TRUNC(DATAHORA) = TRUNC(SYSDATE)-1 THEN TO_NUMBER(REPLACE(VALOR,',','.')) END) AS ONTEM,
       MAX(CASE WHEN TRUNC(DATAHORA) = TRUNC(SYSDATE) THEN TO_NUMBER(REPLACE(VALOR,',','.')) END) AS HOJE,
       AVG(TO_NUMBER(REPLACE(VALOR,',','.'))) AS SAFRA
FROM LABORATORIO.RESULTADO
WHERE COD_SAFRA = :safra
AND TRIM(NOME_VARIAVEL) IN (
  'ART_BA', 'ART_TO', 'PL_TO', 'MD_POL_TO', 'ATR', 'ATR_CONSECANA',
  'FBR_CONSECANA', 'FBR_PCTS', 'GER_TOSHB', 'GER_WEG', 'TOT_GER',
  'PH_CM', 'PH_CF', 'PL_CM', 'PL_CF', 'PR_CM', 'PR_CF',
  'IMP_MINERAL_MANUAL', 'PI_VG_KG', '%IMP_PALHA'
)
GROUP BY TRIM(NOME_VARIAVEL)
